# nginx proxy address - http://172.17.0.1:8080

name: headscale
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: headscale/headscale:latest
    container_name: headscale-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
    ports:
      - '172.17.0.1:8080:8080'
    volumes:
      - './rootfs/data/headscale:/data'
    networks:
      - headscale

networks:
  headscale:
    name: headscale
    external: false
